name: "CI"
on:
  push:
jobs:
  nix-flake-check:
    # TODO idea: instead of using QEMU (which is slow) use the host as remote builder
    strategy:
      matrix:
        system: ["aarch64-linux", "x86_64-linux"]
    runs-on: ubuntu-latest
    name: "Build checks for ${{ matrix.system }}"
    steps:
    - run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_ed25519
        chmod 600 /home/runner/.ssh/id_ed25519
    - run: "[ '${{ matrix.system }}' == 'aarch64-linux' ] && sudo apt-get install -y qemu-user-static || true"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: | 
          system = ${{ matrix.system }}
    - run: |
        nix run .#inject-secrets
    - run: nix flake check -L
